---
image: ${CONTAINER_REGISTRY}/docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  WORKDIR: /tmp

  # To be set externally in GitLab
  # - CONTAINER_REGISTRY_PULL
  # - CONTAINER_REGISTRY_PUSH
  # - REGISTRY_USERNAME
  # - REGISTRY_PASSWORD
  # - REGISTRY_NAMESPACE

stages:
  - build
  - test
  - publish

docker-build:
  stage: build
  tags: [dockersock]
  needs: []
  before_script:
    - docker --version
    - docker login -u "${REGISTRY_USERNAME}" -p "${REGISTRY_PASSWORD}" "${CONTAINER_REGISTRY_PULL}"
    - docker login -u "${REGISTRY_USERNAME}" -p "${REGISTRY_PASSWORD}" "${CONTAINER_REGISTRY_PUSH}"
    - export DOCKER_CONTENT_TRUST=1
  script:
    - >
      docker build
      --pull
      --file Dockerfile
      --cache-from "${CONTAINER_REGISTRY_PULL}/${REGISTRY_NAMESPACE}/resticker:release"
      --label "org.opencontainers.image.title=${CI_PROJECT_TITLE}"
      --label "org.opencontainers.image.created=${CI_JOB_STARTED_AT}"
      --label "org.opencontainers.image.url=${CI_PROJECT_URL}"
      --label "org.opencontainers.image.documentation=${CI_PROJECT_URL}"
      --label "org.opencontainers.image.source=${CI_PROJECT_URL}"
      --label "org.opencontainers.image.authors=${GITLAB_USER_EMAIL}"
      --label "org.opencontainers.image.version=${CI_COMMIT_REF_NAME}"
      --label "org.opencontainers.image.revision=${CI_COMMIT_SHA}"
      --tag "${CONTAINER_REGISTRY_PUSH}/${REGISTRY_NAMESPACE}/resticker:release-${CI_COMMIT_SHORT_SHA}"
      --build-arg BUILDKIT_INLINE_CACHE=1
      "."
  after_script:
    - docker push "${CONTAINER_REGISTRY_PUSH}/${REGISTRY_NAMESPACE}/resticker:release-${CI_COMMIT_SHORT_SHA}"

trivy_fs_scanning:
  image:
    name: "${CONTAINER_REGISTRY_PULL}/${REGISTRY_NAMESPACE}/trivy:latest"
    pull_policy: always
    entrypoint: [""]
  stage: test
  tags: [docker]
  needs: []
  script:
    - trivy --version
    - >
      trivy
      fs
      --scanners vuln,config
      --exit-code 0
      --no-progress
      --format json
      --output "${CI_PROJECT_DIR}/trivy-fs.json"
      "${CI_PROJECT_DIR}"
    # Prints full report
    - trivy fs --scanners vuln,config --exit-code 0 --no-progress "${CI_PROJECT_DIR}"
    # Fail on critical vulnerabilities
    # - time trivy fs --exit-code 1 --severity CRITICAL --no-progress "${CI_PROJECT_DIR}"
  artifacts:
    when: always
    expose_as: "Trivy FS Scan"
    paths:
      - trivy-fs.json

trivy_container_scanning:
  image:
    name: "${CONTAINER_REGISTRY_PULL}/${REGISTRY_NAMESPACE}/trivy:latest"
    pull_policy: always
    entrypoint: [""]
  stage: test
  tags: [docker]
  needs:
    - docker-build
  # when: delayed
  # start_in: 5 seconds
  # retry: 2
  variables:
    # No need to clone the repo, we exclusively work on artifacts.  See
    # https://docs.gitlab.com/ee/ci/runners/README.html#git-strategy
    GIT_STRATEGY: none
    TRIVY_USERNAME: "${REGISTRY_USERNAME}"
    TRIVY_PASSWORD: "${REGISTRY_PASSWORD}"
  script:
    - trivy --version
    - >
      trivy
      image
      --exit-code 0
      --no-progress
      --format json
      --output "${CI_PROJECT_DIR}/trivy-image.json"
      "${CONTAINER_REGISTRY_PULL}/${REGISTRY_NAMESPACE}/resticker:release-${CI_COMMIT_SHORT_SHA}"
    # Prints full report
    - trivy image --exit-code 0 --no-progress "${CONTAINER_REGISTRY_PULL}/${REGISTRY_NAMESPACE}/resticker:release-${CI_COMMIT_SHORT_SHA}"
    # Fail on critical vulnerabilities
    # - time trivy image --exit-code 1 --severity CRITICAL --no-progress "${CONTAINER_REGISTRY_PULL}/${REGISTRY_NAMESPACE}/resticker:release-${CI_COMMIT_SHORT_SHA}"
  artifacts:
    when: always
    expose_as: "Trivy Image Scan"
    paths:
      - trivy-image.json
    # reports:
    #   container_scanning: gl-container-scanning-report.json

dockle:
  image:
    name: "${CONTAINER_REGISTRY_PULL}/goodwithtech/dockle:latest"
    entrypoint: [""]
  stage: test
  tags: [docker]
  needs:
    - docker-build
  # when: delayed
  # start_in: 5 seconds
  # retry: 2
  variables:
    GIT_STRATEGY: none
    DOCKLE_USERNAME: "${REGISTRY_USERNAME}"
    DOCKLE_PASSWORD: "${REGISTRY_PASSWORD}"
  script:
    - dockle -f json -o dockle.json "${CONTAINER_REGISTRY_PULL}/${REGISTRY_NAMESPACE}/resticker:release-${CI_COMMIT_SHORT_SHA}"
  artifacts:
    when: always
    paths:
      - dockle.json

# add additional tags to speed up future builds
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#make-docker-in-docker-builds-faster-with-docker-layer-caching
tag-image:
  stage: publish
  tags: [dockersock]
  variables:
    GIT_STRATEGY: none
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  needs:
    - trivy_container_scanning
    - trivy_fs_scanning
    - dockle
  before_script:
    - docker login -u "${REGISTRY_USERNAME}" -p "${REGISTRY_PASSWORD}" "${CONTAINER_REGISTRY_PUSH}"
  script:
    - docker pull "${CONTAINER_REGISTRY_PUSH}/${REGISTRY_NAMESPACE}/resticker:release-${CI_COMMIT_SHORT_SHA}"
    - docker tag "${CONTAINER_REGISTRY_PUSH}/${REGISTRY_NAMESPACE}/resticker:release-${CI_COMMIT_SHORT_SHA}" "${CONTAINER_REGISTRY_PUSH}/${REGISTRY_NAMESPACE}/resticker:release"
    - docker push "${CONTAINER_REGISTRY_PUSH}/${REGISTRY_NAMESPACE}/resticker:release"

# .defectdojo-upload-base:
#   stage: publish
#   image: docker.io/maibornwolff/dd-import:latest
#   rules:
#     - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
#   tags: [docker]
#   variables:
#     GIT_STRATEGY: none
#   script:
#     - dd-reimport-findings.sh

# upload_dd_trivy_fs_scan:
#   extends: .defectdojo-upload-base
#   needs:
#     - job: trivy_fs_scanning
#       artifacts: true
#   variables:
#     DD_TEST_NAME: "Trivy FS"
#     DD_TEST_TYPE_NAME: "Trivy Scan"
#     DD_FILE_NAME: "trivy-fs.json"

# upload_dd_trivy_image_scan:
#   extends: .defectdojo-upload-base
#   needs:
#     - job: trivy_container_scanning
#       artifacts: true
#   variables:
#     DD_TEST_NAME: "Trivy Image"
#     DD_TEST_TYPE_NAME: "Trivy Scan"
#     DD_FILE_NAME: "trivy-image.json"

# upload_dd_dockle_scan:
#   extends: .defectdojo-upload-base
#   needs:
#     - job: dockle
#       artifacts: true
#   variables:
#     DD_TEST_NAME: "Dockle"
#     DD_TEST_TYPE_NAME: "Dockle Scan"
#     DD_FILE_NAME: "dockle.json"
