#!/bin/bash
set -euo pipefail

# shellcheck source=functions
. /usr/local/bin/functions

main() {
  local start
  local end
  local archive_dir="${RESTIC_REPOSITORY##*/}"
  local backup_password="${RESTIC_PASSWORD}"
  local backup_repo="${RESTIC_REPOSITORY}"
  local archive_repo="${ARCHIVE_REPO_BASEURL}/${archive_dir}"

  local RESTIC_PASSWORD="${ARCHIVE_PASSWORD}"
  # shellcheck disable=SC2034
  local RESTIC_FROM_PASSWORD="${backup_password}"

  start="$(date +%s)"

  log info "archive start" "repo,${archive_repo}"
  set +e
  if ! restic cat --repo="${archive_repo}" config > /dev/null; then
    set -e
    log info "init archive repository" "repo,${archive_repo}"
    restic --repo="${archive_repo}" init --from-repo="${backup_repo}" --copy-chunker-params
  else
    set -e
  fi

  log info "start copy" "repo,${archive_dir}"
  set +e
  # shellcheck disable=SC2086
  if ! restic --from-repo="${backup_repo}" copy --repo="${archive_repo}" ${ARCHIVE_ARGS:-}; then
    set -e
    log error "copy failed" "repo,${archive_repo}"
  else
    set -e
    log info "copy successful" "repo,${archive_repo}"
  fi

  end="$(date +%s)"
  log info "archive end" "repo,${archive_repo}" "duration,$((end-start))"
}

trap run_exit_commands EXIT
if [[ "${ARCHIVE}" == "true" ]]; then
  main "$@"
else
  log warn "archive is disabled globally. exiting"
fi
