#!/bin/bash
set -euo pipefail

source /usr/local/bin/functions

main() {
  run_commands "${PRE_COMMANDS:-}"

  start=$(date +%s)
  echo Starting check at "$(date +"%Y-%m-%d %H:%M:%S")"

  set +e
  if ! restic --repo="${RESTIC_REPOSITORY}" check ${RESTIC_CHECK_ARGS:-}; then
    set -e
    run_commands "${POST_COMMANDS_FAILURE:-}"
    exit
  else
    set -e
  fi

  echo Check successful

  end="$(date +%s)"
  echo Finished check at "$(date +"%Y-%m-%d %H:%M:%S")" after $((end-start)) seconds

  run_commands "${POST_COMMANDS_SUCCESS:-}"
}

trap run_exit_commands EXIT
main "$@"
