#!/bin/bash
set -euo pipefail

source /usr/local/bin/functions

main() {
  run_commands "${PRE_COMMANDS:-}"

  start=$(date +%s)
  log info "Starting check" "repo,${RESTIC_REPOSITORY}"

  set +e
  if ! restic --repo="${RESTIC_REPOSITORY}" check ${RESTIC_CHECK_ARGS:-}; then
    set -e
    run_commands "${POST_COMMANDS_FAILURE:-}"
    exit
  else
    set -e
  fi

  log info "Check successful" "repo,${RESTIC_REPOSITORY}"

  end="$(date +%s)"
  log info "Finished check after $((end-start)) seconds" "repo,${RESTIC_REPOSITORY}"

  run_commands "${POST_COMMANDS_SUCCESS:-}"
}

trap run_exit_commands EXIT
main "$@"
