#!/bin/bash
set -euo pipefail

source /usr/local/bin/functions

declare -A REPOSITORIES

RCLONE_CONFIG_PATH="/run/secrets/rclone.conf"
SSH_CONFIG_PATH="/run/secrets/.ssh"

if [[ -f "$RCLONE_CONFIG_PATH" ]]; then
  mkdir -p /root/.config/rclone
  cp "$RCLONE_CONFIG_PATH" /root/.config/rclone/rclone.conf
fi

if [[ -d "$SSH_CONFIG_PATH" ]]; then
  cp -r "${SSH_CONFIG_PATH}" /root/.ssh
  chmod 700 /root/.ssh
  chmod -R u+rwX,go-rwx /root/.ssh
fi

repo_vars_setup
run init_check

if [[ $# -gt 0 ]]; then
  run restic "$@"
else
  if [[ -n "${BACKUP_CRON:-}" ]] && [[ -n "${PRUNE_CRON:-}" ]]; then
    >&2 echo "Environment variables BACKUP_CRON and PRUNE_CRON are mutually exclusive. Please fix your configuration. Exiting."
    exit 1
  fi
  if [[ -n "${BACKUP_CRON:-}" ]] && [[ -n "${CHECK_CRON:-}" ]]; then
    >&2 echo "Environment variables BACKUP_CRON and CHECK_CRON are mutually exclusive. Please fix your configuration. Exiting."
    exit 1
  fi
  if [[ -n "${PRUNE_CRON:-}" ]] && [[ -n "${CHECK_CRON:-}" ]]; then
    >&2 echo "Environment variables PRUNE_CRON and CHECK_CRON are mutually exclusive. Please fix your configuration. Exiting."
    exit 1
  fi
  if [[ -n "${BACKUP_CRON:-}" ]]; then
    if [ "${RUN_ON_STARTUP:-}" == "true" ]; then
      run backup
    fi
    setup_cron backup "${BACKUP_CRON}"
  fi
  if [[ -n "${PRUNE_CRON:-}" ]]; then
    if [ "${RUN_ON_STARTUP:-}" == "true" ]; then
      run prune
    fi
    setup_cron prune "${PRUNE_CRON}"
  fi
  if [[ -n "${CHECK_CRON:-}" ]]; then
    if [ "${RUN_ON_STARTUP:-}" == "true" ]; then
      run check
    fi
    setup_cron check "${CHECK_CRON}"
  fi
  >&2 echo "No valid operating mode configured! Exiting."
  exit 1
fi
