#!/bin/bash

run_commands() {
  COMMANDS=$1
  while IFS= read -r cmd; do echo "$cmd" && eval "$cmd" ; done < <(printf '%s\n' "$COMMANDS")
}

run_exit_commands() {
  set +e
  set +o pipefail
  run_commands "${POST_COMMANDS_EXIT:-}"
}

replace_spaces() {
  echo "${1/\\ /\\}"
}

replace_spaces_back() {
  echo "${1/\\/ }"
}

log() {
  # extra labels can be defined as "key,value" entries to the function call
  declare level="$1"
  declare message="$2"
  shift 2
  declare -a extra_data=( "${@}" )
  declare logline
  declare extra_labels=""
  declare timestamp
  timestamp="$(date -Ins)"

  # formatting of the extra labels
  if (( "${#extra_data[@]}" > 0 )); then
    for entry in "${extra_data[@]}"; do
      while IFS="," read -r lkey lvalue; do
        if [[ "${LOGFORMAT}" == "json" ]]; then
          extra_labels=$(printf '%s,"%s":"%s"' "${extra_labels}" "${lkey}" "${lvalue}")
        else
          extra_labels=$(printf '%s %s=%s' "${extra_labels:- -}" "${lkey}" "${lvalue}")
        fi
      done <<< "${entry}"
    done
  fi

  # formatting of the final logline
  if [[ "${LOGFORMAT}" == "json" ]]; then
    logline=$(printf '{"timestamp":"%s","level":"%s","message":"%s"%s}' "${timestamp}" "${level}" "${message}" "${extra_labels}")
  else
    logline=$(printf '%s [%s] %s%s' "${timestamp}" "${level}" "${message}" "${extra_labels}")
  fi

  echo -e "${logline}"
}

repo_vars_setup() {
  if [[ "${MULTIREPO:-}" == "true" ]]; then
    if [[ -r "${MULTIREPO_CONFIG_PATH}" ]]; then
      while read -r repo password; do
        REPOSITORIES["$repo"]="$password"
      done < "${MULTIREPO_CONFIG_PATH}"
      log info "${#REPOSITORIES[@]} repository configs loaded" "file,${MULTIREPO_CONFIG_PATH}"
    else
      log error "Could not read repository configuration" "file,${MULTIREPO_CONFIG_PATH}"
      exit 1
    fi
  else
    REPOSITORIES["${RESTIC_REPOSITORY}"]="${RESTIC_PASSWORD}"
  fi
}

# This only works properly when doing daily backups
# If there are multiple manual backups on one of these special days,
# manual cleanup needs to be performed on duplicate tags
# Returns: the list of extra Tags
extra_tags() {
  local -a etags
  # if (( "$(date +'%u')" == 1 )); then etags+=("WEEKLY"); fi
  if (( "$(date +'%d')" == 1 )); then etags+=("MONTHLY"); fi
  if (( "$(date +'%j')" == 1 )); then etags+=("YEARLY"); fi
  echo "${etags[@]}"
}

init_check() {
  log info "Checking configured repository" "repo,${RESTIC_REPOSITORY}"
  if restic cat config > /dev/null; then
    log info "Repository found." "repo,${RESTIC_REPOSITORY}"
  else
    log warn "Could not access the configured repository. Trying to initialize (in case it has not been initialized yet) ..." "repo,${RESTIC_REPOSITORY}"
    if restic init; then
      log info "Repository successfully initialized." "repo,${RESTIC_REPOSITORY}"
    else
      if [ "${SKIP_INIT_CHECK:-}" == "true" ]; then
        log warn "Initialization failed. Ignoring errors because SKIP_INIT_CHECK is set in your configuration." "repo,${RESTIC_REPOSITORY}"
      else
        log error "Initialization failed. Please see error messages above and check your configuration. Exiting." "repo,${RESTIC_REPOSITORY}"
        exit 1
      fi
    fi
  fi
}

run() {
  local action="${1}"
  shift
  for repo in "${!REPOSITORIES[@]}"; do

    export RESTIC_REPOSITORY="${repo}"
    export RESTIC_PASSWORD="${REPOSITORIES[${repo}]}"

    log info "Executing ${action}" "repo,${RESTIC_REPOSITORY}"
    case ${action} in
      backup | check | prune | archive | restic)
        /usr/local/bin/"${action}" "$@"
        ;;
      init_check)
        init_check
        ;;
      *)
        log error "${action} is not defined"
    esac
  done
}

setup_cron() {
  local action=${1}
  local cron_expr=${2}
  log info "Scheduling ${action} job according to cron expression."
  exec go-cron "${cron_expr}" /usr/local/bin/repo_wrapper "${action}"
}
