#!/bin/bash
set -euo pipefail

source /usr/local/bin/functions

main() {
  run_commands "${PRE_COMMANDS:-}"

  start=$(date +%s)

  if [ -n "${RESTIC_FORGET_ARGS:-}" ]; then
    echo Forget about old snapshots based on RESTIC_FORGET_ARGS = ${RESTIC_FORGET_ARGS}
    restic forget ${RESTIC_FORGET_ARGS}
  fi

  echo Starting prune at "$(date +"%Y-%m-%d %H:%M:%S")"

  set +e
  if ! restic --repo="${RESTIC_REPOSITORY}" prune ${RESTIC_PRUNE_ARGS:-} ; then
    set -e
    run_commands "${POST_COMMANDS_FAILURE:-}"
    exit
  else
    set -e
  fi

  echo Prune successful

  end="$(date +%s)"
  echo Finished prune at "$(date +"%Y-%m-%d %H:%M:%S")" after $((end-start)) seconds

  run_commands "${POST_COMMANDS_SUCCESS:-}"
}

trap run_exit_commands EXIT
main "$@"
