#!/bin/bash
set -euo pipefail

# shellcheck source=functions
source /usr/local/bin/functions

main() {
  run_commands "${PRE_COMMANDS:-}"

  start=$(date +%s)

  if [[ "${ARCHIVE}" == "true" ]]; then
    # shellcheck source=archive
    . /usr/local/bin/archive
  fi

  if [[ -n "${RESTIC_FORGET_ARGS:-}" ]]; then
    log info "Forget about old snapshots based on RESTIC_FORGET_ARGS - ${RESTIC_FORGET_ARGS}"
    # shellcheck disable=SC2086
    restic forget ${RESTIC_FORGET_ARGS}
  fi

  log info "Starting prune" "repo,${RESTIC_REPOSITORY}"

  set +e
  # shellcheck disable=SC2086
  if ! restic --repo="${RESTIC_REPOSITORY}" prune ${RESTIC_PRUNE_ARGS:-} ; then
    set -e
    run_commands "${POST_COMMANDS_FAILURE:-}"
    exit
  else
    set -e
  fi

  log info "Prune successful" "repo,${RESTIC_REPOSITORY}"

  end="$(date +%s)"
  log info "Finished prune after $((end-start)) seconds" "repo,${RESTIC_REPOSITORY}"

  run_commands "${POST_COMMANDS_SUCCESS:-}"
}

trap run_exit_commands EXIT
main "$@"
